OTHER = "Other"

CITYSCAPE = "Cityscape"
LEGISTAR = "Legistar"
PLANNING = "Planning Commission"
DATA_PORTAL = "Data Portal"

SOURCE_OPTIONS = [CITYSCAPE, LEGISTAR, PLANNING, DATA_PORTAL, OTHER]

ZONING_CHANGE = "Zoning Change"
AIR_POLLUTION = "Air Pollution Permit"
ASBESTOS_DEMOLITION = "Asbestos Demolition"

CATEGORY_OPTIONS = [ZONING_CHANGE, AIR_POLLUTION, ASBESTOS_DEMOLITION, OTHER]
