name: CI

on: [push, pull_request]

env:
  CI: true
  PIPENV_VENV_IN_PROJECT: true
  AUTOTHROTTLE_MAX_DELAY: 30.0
  AUTOTHROTTLE_START_DELAY: 1.5
  AUTOTHROTTLE_TARGET_CONCURRENCY: 3.0

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: pipenv sync --dev
        env:
          PIPENV_DEFAULT_PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Check imports with isort
        run: pipenv run isort . --check-only

      - name: Check style with black
        run: pipenv run black . --check

      - name: Lint with flake8
        run: pipenv run flake8 .

      - name: Test with pytest
        run: pipenv run pytest
