name: CI

on: [push, pull_request]

env:
  CI: true
  AUTOTHROTTLE_MAX_DELAY: 30.0
  AUTOTHROTTLE_START_DELAY: 1.5
  AUTOTHROTTLE_TARGET_CONCURRENCY: 3.0

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Check imports with isort
        run: poetry run isort . --check-only

      - name: Check style with black
        run: poetry run black . --check

      - name: Lint with flake8
        run: poetry run flake8 .

      - name: Test with pytest
        run: poetry run pytest
