name: Cron

on:
  schedule:
    - cron: "12 8 * * *"
  workflow_dispatch:

env:
  CI: true
  SCRAPY_SETTINGS_MODULE: tdl_scrapers.settings.prod
  AUTOTHROTTLE_MAX_DELAY: 30.0
  AUTOTHROTTLE_START_DELAY: 1.5
  AUTOTHROTTLE_TARGET_CONCURRENCY: 3.0

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Run scrapers
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
          ./.deploy.sh

      - name: Export to Airtable
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
          poetry run scrapy update_airtable
